[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  # Comma-separated list of env vars to ignore in secrets scanning
  SECRETS_SCAN_OMIT_KEYS = "VITE_FIREBASE_API_KEY,VITE_FIREBASE_APP_ID,VITE_FIREBASE_MESSAGING_SENDER_ID"

[dev]
  command = "npm run dev"
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200